[package]
name = "host"
version = "0.0.1"
edition = "2021"

[dependencies]
cobs = { version = "0.3.0" , default-features = false }
serde = { version = "1.0.218" , default-features = false, features = ["derive"]}
serde_cbor = { version = "0.11.2", default-features = false, features = ["alloc"] }
shared = { path = "../shared" }