[package]
name = "host"
description = "The code that will run on the host environment hosting the enclave"
version = "0.0.1"
edition = "2024"

[dependencies]
serde_cbor.workspace = true
shared = { path = "../shared", features = ["std"] }
tracing.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true