[package]
name = "host"
description = "The code that will run on the host environment hosting the enclave"
version = "0.0.1"
edition = "2024"

[dependencies]
serde_cbor.workspace = true
shared = { path = "../shared" }
tracing.workspace = true