[package]
name = "fmd-enclave-service"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218" , default-features = false, features = ["derive"]}
shared = { path = "../shared" }


[dependencies.ostd]
version = "0.11.3"

[workspace]
exclude = ["target/osdk/base", "target/osdk/test-base"]
